// <auto-generated />
using System;
using LightenUp.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightenUp.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610034918_RemovePatientDepartment")]
    partial class RemovePatientDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyPsychologist", b =>
                {
                    b.Property<int>("PartneredCompaniesCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("PartneredPsychologistsPsychologistId")
                        .HasColumnType("int");

                    b.HasKey("PartneredCompaniesCompanyId", "PartneredPsychologistsPsychologistId");

                    b.HasIndex("PartneredPsychologistsPsychologistId");

                    b.ToTable("CompanyPsychologist");
                });

            modelBuilder.Entity("LightenUp.Web.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApprovedByAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LightenUp.Web.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ReferralCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.HasIndex("ReferralCode")
                        .IsUnique()
                        .HasFilter("[ReferralCode] IS NOT NULL");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("LightenUp.Web.Models.CompanyDivision", b =>
                {
                    b.Property<int>("DivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivisionId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferralCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DivisionId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ReferralCode")
                        .IsUnique()
                        .HasFilter("[ReferralCode] IS NOT NULL");

                    b.ToTable("CompanyDivisions");
                });

            modelBuilder.Entity("LightenUp.Web.Models.CompanySubscription", b =>
                {
                    b.Property<int>("CompanySubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanySubscriptionId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxSessionsPerMonth")
                        .HasColumnType("int");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanySubscriptionId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanySubscriptions");
                });

            modelBuilder.Entity("LightenUp.Web.Models.HrEmployeeRemovalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecisionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionByAdminUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RequestedByHrUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("DecisionByAdminUserId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RequestedByHrUserId");

                    b.ToTable("HrEmployeeRemovalRequests");
                });

            modelBuilder.Entity("LightenUp.Web.Models.HrNotificationPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowEmployeePsyNotif")
                        .HasColumnType("bit");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("HrId")
                        .HasColumnType("int");

                    b.Property<bool>("RemindCounselingSession")
                        .HasColumnType("bit");

                    b.Property<bool>("RemindEmployeeCheck")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HrId")
                        .IsUnique();

                    b.ToTable("HrNotificationPreferences");
                });

            modelBuilder.Entity("LightenUp.Web.Models.HrStaff", b =>
                {
                    b.Property<int>("HrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HrId"));

                    b.Property<string>("AcademicDocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastDegree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OnboardingCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupportDocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("HrId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("HrStaffs");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Journal", b =>
                {
                    b.Property<int>("JournalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JournalId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("JournalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("JournalId");

                    b.HasIndex("PatientId", "JournalDate")
                        .IsUnique();

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("LightenUp.Web.Models.JournalCheckIn", b =>
                {
                    b.Property<int>("CheckInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckInId"));

                    b.Property<int>("AnxietyScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmotionScore")
                        .HasColumnType("int");

                    b.Property<int>("FocusScore")
                        .HasColumnType("int");

                    b.Property<int>("MindLoadScore")
                        .HasColumnType("int");

                    b.Property<int>("OverallScore")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SleepScore")
                        .HasColumnType("int");

                    b.HasKey("CheckInId");

                    b.HasIndex("PatientId", "CheckInDate")
                        .IsUnique();

                    b.ToTable("JournalCheckIns");
                });

            modelBuilder.Entity("LightenUp.Web.Models.MonthlyPayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProofOfTransferFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistId");

                    b.ToTable("MonthlyPayouts");
                });

            modelBuilder.Entity("LightenUp.Web.Models.MoodTracker", b =>
                {
                    b.Property<int>("MoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoodId"));

                    b.Property<int?>("AnxietyScore")
                        .HasColumnType("int");

                    b.Property<int?>("EmotionScore")
                        .HasColumnType("int");

                    b.Property<string>("Feeling")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("FocusScore")
                        .HasColumnType("int");

                    b.Property<int?>("MindLoadScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("MoodDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SleepScore")
                        .HasColumnType("int");

                    b.Property<string>("Triggers")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("MoodId");

                    b.HasIndex("PatientId", "MoodDate")
                        .IsUnique();

                    b.ToTable("MoodTrackers");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("AppGoals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CounselingMethodOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CounselingMethods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("EmergencyContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactRelation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasMedicationHistory")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasPreviousCounseling")
                        .HasColumnType("bit");

                    b.Property<string>("MentalHealthStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OnboardingCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RelationshipStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SleepQuality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpiritualActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TermsAcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PatientId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("CompanyId", "EmployeeId")
                        .IsUnique()
                        .HasFilter("[CompanyId] IS NOT NULL AND [EmployeeId] IS NOT NULL");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("LightenUp.Web.Models.PatientAdminAssignmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedByAdminUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AssignedPsychologistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecisionAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PreferredPsychologistId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByAdminUserId");

                    b.HasIndex("AssignedPsychologistId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PreferredPsychologistId");

                    b.ToTable("PatientAdminAssignmentRequests");
                });

            modelBuilder.Entity("LightenUp.Web.Models.PatientNotificationPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowHrPsychologistNotif")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<bool>("RemindCounselingSession")
                        .HasColumnType("bit");

                    b.Property<bool>("RemindMoodCheck")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("ReminderTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("PatientNotificationPreferences");
                });

            modelBuilder.Entity("LightenUp.Web.Models.PatientPsychologistAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedByHrUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CancellationRequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancellationRequestedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DecisionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("MaxSessionsPerMonth")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PsychologistRevenuePercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RequestedByRole")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RequestedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("SlotValue")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("AssignedByHrUserId");

                    b.HasIndex("CancellationRequestedByUserId");

                    b.HasIndex("DecisionByUserId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("LightenUp.Web.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("CallbackPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanySubscriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuitkuReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MerchantOrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PaymentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResultCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ResultMessage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanySubscriptionId");

                    b.HasIndex("MerchantOrderId")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("LightenUp.Web.Models.PendingEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClaimedByPatientId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimedByPatientId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("CompanyId", "Email")
                        .IsUnique();

                    b.ToTable("PendingEmployees");
                });

            modelBuilder.Entity("LightenUp.Web.Models.PsyNotificationPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowHrPatientNotif")
                        .HasColumnType("bit");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<bool>("RemindFollowUp")
                        .HasColumnType("bit");

                    b.Property<bool>("RemindNewReports")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistId")
                        .IsUnique();

                    b.ToTable("PsyNotificationPreferences");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Psychologist", b =>
                {
                    b.Property<int>("PsychologistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PsychologistId"));

                    b.Property<string>("AcademicDocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AcceptsB2B")
                        .HasColumnType("bit");

                    b.Property<string>("AvailabilityText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LastDegree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OnboardingCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PracticeLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiapNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrDocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PsychologistId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Psychologists");
                });

            modelBuilder.Entity("LightenUp.Web.Models.PsychologistPayrollSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgreementStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("BankDetailsPdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("ProposedPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<decimal>("PsychologistPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SessionRate")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByAdminUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistId")
                        .IsUnique();

                    b.HasIndex("UpdatedByAdminUserId");

                    b.ToTable("PayrollSettings");
                });

            modelBuilder.Entity("LightenUp.Web.Models.PsychologistRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProposedDeadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProposedSessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProposedTaskName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RequestedByHrUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RequestedByPatientUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RequesterRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RespondedNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("RequestedByHrUserId");

                    b.HasIndex("RequestedByPatientUserId");

                    b.ToTable("PsychologistRequests");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("EmailBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailSubject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HrRecipientUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<string>("ReportedByHrUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReportedByPsyUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("HrRecipientUserId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("ReportedByHrUserId");

                    b.HasIndex("ReportedByPsyUserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<decimal?>("AppliedPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionStart")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SlotValue")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScheduleId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PsychologistId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxSessionsPerMonth")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("PatientId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Worksheet", b =>
                {
                    b.Property<int>("WorksheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorksheetId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HrNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ProofImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PsychologistFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorksheetId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PsychologistId");

                    b.ToTable("Worksheets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CompanyPsychologist", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Company", null)
                        .WithMany()
                        .HasForeignKey("PartneredCompaniesCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LightenUp.Web.Models.Psychologist", null)
                        .WithMany()
                        .HasForeignKey("PartneredPsychologistsPsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LightenUp.Web.Models.CompanyDivision", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Company", "Company")
                        .WithMany("Divisions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("LightenUp.Web.Models.CompanySubscription", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Company", "Company")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("LightenUp.Web.Models.HrEmployeeRemovalRequest", b =>
                {
                    b.HasOne("LightenUp.Web.Models.ApplicationUser", "DecisionByAdmin")
                        .WithMany()
                        .HasForeignKey("DecisionByAdminUserId");

                    b.HasOne("LightenUp.Web.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LightenUp.Web.Models.ApplicationUser", "RequestedByHr")
                        .WithMany()
                        .HasForeignKey("RequestedByHrUserId");

                    b.Navigation("DecisionByAdmin");

                    b.Navigation("Patient");

                    b.Navigation("RequestedByHr");
                });

            modelBuilder.Entity("LightenUp.Web.Models.HrNotificationPreference", b =>
                {
                    b.HasOne("LightenUp.Web.Models.HrStaff", "Hr")
                        .WithOne("NotificationPreference")
                        .HasForeignKey("LightenUp.Web.Models.HrNotificationPreference", "HrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hr");
                });

            modelBuilder.Entity("LightenUp.Web.Models.HrStaff", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Company", "Company")
                        .WithMany("HrStaffs")
                        .HasForeignKey("CompanyId");

                    b.HasOne("LightenUp.Web.Models.ApplicationUser", "User")
                        .WithOne("HrStaff")
                        .HasForeignKey("LightenUp.Web.Models.HrStaff", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Journal", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Patient", "Patient")
                        .WithMany("Journals")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LightenUp.Web.Models.JournalCheckIn", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Patient", "Patient")
                        .WithMany("JournalCheckIns")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LightenUp.Web.Models.MonthlyPayout", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Psychologist", "Psychologist")
                        .WithMany()
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("LightenUp.Web.Models.MoodTracker", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Patient", "Patient")
                        .WithMany("MoodLogs")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Patient", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Company", "Company")
                        .WithMany("Patients")
                        .HasForeignKey("CompanyId");

                    b.HasOne("LightenUp.Web.Models.CompanyDivision", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId");

                    b.HasOne("LightenUp.Web.Models.ApplicationUser", "User")
                        .WithOne("Patient")
                        .HasForeignKey("LightenUp.Web.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Division");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LightenUp.Web.Models.PatientAdminAssignmentRequest", b =>
                {
                    b.HasOne("LightenUp.Web.Models.ApplicationUser", "AssignedByAdmin")
                        .WithMany()
                        .HasForeignKey("AssignedByAdminUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LightenUp.Web.Models.Psychologist", "AssignedPsychologist")
                        .WithMany()
                        .HasForeignKey("AssignedPsychologistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LightenUp.Web.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LightenUp.Web.Models.Psychologist", "PreferredPsychologist")
                        .WithMany()
                        .HasForeignKey("PreferredPsychologistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedByAdmin");

                    b.Navigation("AssignedPsychologist");

                    b.Navigation("Patient");

                    b.Navigation("PreferredPsychologist");
                });

            modelBuilder.Entity("LightenUp.Web.Models.PatientNotificationPreference", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Patient", "Patient")
                        .WithOne("NotificationPreference")
                        .HasForeignKey("LightenUp.Web.Models.PatientNotificationPreference", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LightenUp.Web.Models.PatientPsychologistAssignment", b =>
                {
                    b.HasOne("LightenUp.Web.Models.ApplicationUser", "AssignedByHr")
                        .WithMany()
                        .HasForeignKey("AssignedByHrUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LightenUp.Web.Models.ApplicationUser", "CancellationRequestedBy")
                        .WithMany()
                        .HasForeignKey("CancellationRequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LightenUp.Web.Models.ApplicationUser", "DecisionBy")
                        .WithMany()
                        .HasForeignKey("DecisionByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LightenUp.Web.Models.Patient", "Patient")
                        .WithMany("Assignments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LightenUp.Web.Models.Psychologist", "Psychologist")
                        .WithMany("Assignments")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LightenUp.Web.Models.ApplicationUser", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedByHr");

                    b.Navigation("CancellationRequestedBy");

                    b.Navigation("DecisionBy");

                    b.Navigation("Patient");

                    b.Navigation("Psychologist");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("LightenUp.Web.Models.PaymentTransaction", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LightenUp.Web.Models.CompanySubscription", "CompanySubscription")
                        .WithMany("Payments")
                        .HasForeignKey("CompanySubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LightenUp.Web.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LightenUp.Web.Models.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("CompanySubscription");

                    b.Navigation("Patient");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("LightenUp.Web.Models.PendingEmployee", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Patient", "ClaimedByPatient")
                        .WithMany()
                        .HasForeignKey("ClaimedByPatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LightenUp.Web.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LightenUp.Web.Models.CompanyDivision", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId");

                    b.Navigation("ClaimedByPatient");

                    b.Navigation("Company");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("LightenUp.Web.Models.PsyNotificationPreference", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Psychologist", "Psychologist")
                        .WithOne("NotificationPreference")
                        .HasForeignKey("LightenUp.Web.Models.PsyNotificationPreference", "PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Psychologist", b =>
                {
                    b.HasOne("LightenUp.Web.Models.ApplicationUser", "User")
                        .WithOne("Psychologist")
                        .HasForeignKey("LightenUp.Web.Models.Psychologist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LightenUp.Web.Models.PsychologistPayrollSetting", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Psychologist", "Psychologist")
                        .WithMany()
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LightenUp.Web.Models.ApplicationUser", "UpdatedByAdmin")
                        .WithMany()
                        .HasForeignKey("UpdatedByAdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Psychologist");

                    b.Navigation("UpdatedByAdmin");
                });

            modelBuilder.Entity("LightenUp.Web.Models.PsychologistRequest", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LightenUp.Web.Models.Psychologist", "Psychologist")
                        .WithMany()
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LightenUp.Web.Models.ApplicationUser", "RequestedByHr")
                        .WithMany()
                        .HasForeignKey("RequestedByHrUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LightenUp.Web.Models.ApplicationUser", "RequestedByPatient")
                        .WithMany()
                        .HasForeignKey("RequestedByPatientUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Patient");

                    b.Navigation("Psychologist");

                    b.Navigation("RequestedByHr");

                    b.Navigation("RequestedByPatient");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Report", b =>
                {
                    b.HasOne("LightenUp.Web.Models.ApplicationUser", "HrRecipient")
                        .WithMany()
                        .HasForeignKey("HrRecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LightenUp.Web.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LightenUp.Web.Models.Psychologist", "Psychologist")
                        .WithMany()
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LightenUp.Web.Models.ApplicationUser", "ReportedByHr")
                        .WithMany()
                        .HasForeignKey("ReportedByHrUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LightenUp.Web.Models.ApplicationUser", "ReportedByPsy")
                        .WithMany()
                        .HasForeignKey("ReportedByPsyUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HrRecipient");

                    b.Navigation("Patient");

                    b.Navigation("Psychologist");

                    b.Navigation("ReportedByHr");

                    b.Navigation("ReportedByPsy");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Schedule", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Patient", "Patient")
                        .WithMany("Schedules")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LightenUp.Web.Models.Psychologist", "Psychologist")
                        .WithMany("Schedules")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Subscription", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Patient", "Patient")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Worksheet", b =>
                {
                    b.HasOne("LightenUp.Web.Models.Patient", "Patient")
                        .WithMany("Worksheets")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LightenUp.Web.Models.Psychologist", "Psychologist")
                        .WithMany("Worksheets")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LightenUp.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LightenUp.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LightenUp.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LightenUp.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LightenUp.Web.Models.ApplicationUser", b =>
                {
                    b.Navigation("HrStaff");

                    b.Navigation("Patient");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Company", b =>
                {
                    b.Navigation("Divisions");

                    b.Navigation("HrStaffs");

                    b.Navigation("Patients");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("LightenUp.Web.Models.CompanySubscription", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LightenUp.Web.Models.HrStaff", b =>
                {
                    b.Navigation("NotificationPreference");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Patient", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("JournalCheckIns");

                    b.Navigation("Journals");

                    b.Navigation("MoodLogs");

                    b.Navigation("NotificationPreference");

                    b.Navigation("Schedules");

                    b.Navigation("Subscriptions");

                    b.Navigation("Worksheets");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Psychologist", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("NotificationPreference");

                    b.Navigation("Schedules");

                    b.Navigation("Worksheets");
                });

            modelBuilder.Entity("LightenUp.Web.Models.Subscription", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
